version: '3'
services:
  lp2:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: lp2
    ports:
      - "9001:3306"
    volumes:
      - ./data:/var/lib/mysql
